apiVersion: v1
kind: Service
metadata:
  name: svc-go-graceful-shutdown
  namespace: test-c
spec:
  ports:
  - name: backend
    port: 8000
    targetPort: 8000
  selector:
    app: go-graceful-shutdown
  type: LoadBalancer
